name: setup environment
description: setup environment for CI and install dependencies

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: >
        sudo apt-get -qq update &&
        sudo apt-get -qq install -y
        software-properties-common &&
        sudo add-apt-repository ppa:deadsnakes/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq install -y
        cmake
        jq
        gcc
        libyaml-cpp-dev
        python3.10
        python3.10-venv
        python3-pip
        python3-pybind11
      shell: bash

    - name: install eigen 3.4.0
      run: |
        sudo bash .github/scripts/install_eigen.sh
      shell: bash

    - name: installation of this repository
      run: sudo pip3 install .
      shell: bash

    - name: install pip packages
      run: pip3 install -r requirements.txt
      shell: bash