# see: https://github.com/rami3l/plfl/blob/master/.github/workflows/ci.yml
name: CI

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup and install dependencies
        uses: ./.github/actions/setup

      - name: test for building `vehicle_adaptor_compensator.cpp`
        run: python3 build_test.py

      - name: test for building `actuation_map_2d.cpp`
        run: python3 build_actuation_map_2d_test.py

  run_simulator:
    runs-on: self-hosted
    needs: build_test
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup and install dependencies
        uses: ./.github/actions/setup

      - name: test for python simulator
        run: |
          cd autoware_vehicle_adaptor/python_simulator
          python3 run_vehicle_adaptor.py
          cd ../..

      - name: test for calibration simulator
        run: |
          cd autoware_vehicle_adaptor/python_simulator
          python3 run_accel_brake_map_calibrator.py
          cd ../..

      - name: Get current date and time
        env:
          TZ: "Asia/Tokyo"
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: upload log to artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.date.outputs.date }}-log-data"
          path: "autoware_vehicle_adaptor/python_simulator/log_data/"
          # artifact は一週間だけ保持
          retention-days: 7
          if-no-files-found: warn
